### ISSUE TITLE
RFMaterial Component -> Mu bugged

### ISSUE THREAD

**Issue by LHesse2** [diego-apellaniz/Parametric-FEM-Toolbox#1]
Hey,
The RFMaterial Component seems to have an issue with the advanced parameter G for the 'poisson ratio'.
If I put in a value in GH, the created Material in RFEM gets another value.

**Comment by LHesse2** [comment]
Nevermind.
RFEM overwrites the Value of the poisson ratio instantly due to the set E and G value.

**Comment by diego-apellaniz** [comment]
Thanks for pointing it out!
