### ISSUE TITLE
RF Surface -> Surface Axes Direction doesn't work

### ISSUE THREAD

**Issue by LHesse2** [diego-apellaniz/Parametric-FEM-Toolbox#2]
Hello there,
I can't get the 'Dir' input of the RFSurface Component to work.
The infomation text lists up strings but it only takes integer values without error.
It also takes only the value 1, and 10, 11, ...
If I set for example 10 as input value nothing changes in RFEM.
The value list also doesn't work for this parameter.

**Comment by diego-apellaniz** [comment]
Hi,

the enumeration parameters are supposed to work with GH value lists (see plugin example files). Also the warning messages of the components might also have information sayinw which parameters are missing. This is an example of an RFEM surface with custom orientation:

![image](https://user-images.githubusercontent.com/48953695/125021059-37b25c80-e07a-11eb-932f-9d78532a8cb7.png)

**Comment by LHesse2** [comment]
Thank you very much for the explanation.
Seems that I'm again too dump to use your components. :)

My problem are these generated surfaces whose z-axis-orientation seems to be randomly chosen.
Do you have any idea how to solve this with your tool?
![image](https://user-images.githubusercontent.com/87070933/125040528-0ea0c480-e098-11eb-880f-ed413e52ea6a.png)

**Comment by diego-apellaniz** [comment]
Sure no problem :) 

With the API it is only possible to control de orientation of the X and Y axes and there is no way of knowing which direction of the Z axis RFEM will assign to new surfaces. What you can do though is to use the RF Surface in Disassemble mode and get the orientation of the Z axis of the imported surfaces:

![image](https://user-images.githubusercontent.com/48953695/125052602-6fce9500-e0a4-11eb-803c-c259826dfead.png)

**Comment by LHesse2** [comment]
Thank you very very much again!
At least I can choose the load orientation according to the generated axis then.

Btw the tool is really awesome :)
Have a nice day!
