### ISSUE TITLE
Deleting RF PolyLoad Data doesn't work

### ISSUE THREAD

**Issue by LHesse2** [diego-apellaniz/Parametric-FEM-Toolbox#3]
Hello there again,
I'm not able to delete PolyLoads in RFEM with the Parametric FEM Toolbox.
First I'm using 'Get Data' with PolyLoads set to true.
These PolyLoads I'm feeding into the 'RF PolyLoad' Data Node of the Assemble 'RF PolyLoad' component with delete set to true.
Then I'm feeding these PolyLoads into the 'Set Data' component.
The data is getting through and I flattened the input but nothing changes in RFEm if I set the 'Get Data' and Set'Data' component to true.

![image](https://user-images.githubusercontent.com/87070933/126281484-b190a636-34c0-45bb-895a-262ff194ac21.png)

I use this workflow for many other RFEM Data types and it works.

What am I missing or is this an actual bug?
Thank you very much!

**Comment by diego-apellaniz** [comment]
Hello, you're right there was actually a bug here. Sorry. I have released a version v1.3.2 in which this issue should be fixed - see releases.
Thanks for pointing it out!
Best,
Diego

**Comment by LHesse2** [comment]
Hello,
Thank you very much for this really fast bugfix.
I tested the new release and it works fine now!

But it seems that the RF LoadCase component has the same issue. If I use the same workflow as before, the load cases stay in RFEM. 
No need to fix this one as fast as the last one for me. :)

Greetings,
Lukas

**Comment by diego-apellaniz** [comment]
Hello Lukas,

you're right again, thanks! I've just fixed the bug for Load Cases, Load Combos and Result Combinations. See release v1.3.5.

Best regards,
Diego

**Comment by LHesse2** [comment]
Thank you very much for alle the work you put into this! :)
