### ISSUE TITLE
Line release

### ISSUE THREAD

**Issue by gregoryquinn** [diego-apellaniz/Parametric-FEM-Toolbox#5]
Hi Diego,
any plans to include line releases? Or is that functionality already hiding in an existing component?

Thanks :)
Greg

**Comment by diego-apellaniz** [comment]
Hi Greg,

line relaeses are not implemented yet, but you can use Line Hinges to model a discontinuity between two surfaces, in case it helps:

![2021-11-08 07_44_16-Grasshopper - linienGelenk_test_](https://user-images.githubusercontent.com/48953695/140696017-cb473208-8106-4122-b03d-a3e05f375b85.png)

BR Diego
