### ISSUE TITLE
Download doesn't work

### ISSUE THREAD

**Issue by Hazelnutbrown** [diego-apellaniz/Parametric-FEM-Toolbox#7]
Hi,

I tried downloading and using the provided file. When I open grasshopper this messagebox is shown to me.
![image](https://user-images.githubusercontent.com/105540209/168418268-d4873ba3-1019-4b95-87f9-242196da9b7d.png)

Is there a way to make it work anyways?
Thanks.

**Comment by diego-apellaniz** [comment]
Hello,

you have to update Rhino and then it should work.

Best regards,
Diego
