### ISSUE TITLE
Generated Loads - From Area Loads via Plane

### ISSUE THREAD

**Issue by Zeinoel** [diego-apellaniz/Parametric-FEM-Toolbox#8]
Hi Diego,

is there an equivalent feature in your tool to the RFEM feature "Generated Loads - From Area Loads via Plane" or any other possibility to receive the same?

Kind regards

**Comment by diego-apellaniz** [comment]
Hello,

I'm sorry but the automatic generation of loads is not included in the RF-COM API and therefore I can't included in the Toolbox...

Kind regards,
Diego
